<?php
/**
 * @file
 * Searching for the string the pages of the newspaper $pid
 * Returns the pids of the pages whic are children of newspaper $pid
 */

 /**
  * Implements hook_menu().
  */
function islandora_newspaper_search_inside_menu() {
  $items = array();
  $items['newspaper/search/results-tpl'] = array(
      'title' => 'Search inside newspaper results.',
      'page callback' => 'islandora_newspaper_search_inside_temp',
      'access callback' => TRUE,
  );
  return $items;
}

function islandora_newspaper_search_inside_temp() {
    return theme('islandora_newspaper_search_inside_temp_tpl');
}

function islandora_newspaper_search_inside_theme() {
  module_load_include('inc','islandora_newspaper_search_inside','includes/block.form');
  module_load_include('inc','islandora_newspaper_search_inside','includes/results.form');
  return array(
    'islandora_newspaper_search_inside_temp_tpl' => array(
      'template' => 'theme/temp',
    ),
  );
}

/**
 * Preprocessing the links for the template.
 */

function islandora_newspaper_search_inside_preprocess_islandora_newspaper_search_inside_temp_tpl(&$variables){
  module_load_include('inc','islandora_newspaper_search_inside','includes/block.form');
  module_load_include('inc','islandora_newspaper_search_inside','includes/results.form');
  $params = drupal_get_query_parameters();
  $n = array();
  $n = count($params);
  $variables['search'] = $params[$n-1];
  unset($params[$n-1]);
  $variables['n'] = count($params);
  $variables['pids'] = $params;
  foreach ($params as $pid) {
    $obj = islandora_object_load($pid);
    $variables[$pid]['label'] = $obj->label;
    $variables[$pid]['path'] = '/islandora/object/' . $obj->id;
    $variables[$pid]['ocr_view'] = '/islandora/object/' . $obj->id . '/datastream/OCR/view';
    $variables[$pid]['tn_link'] = '/islandora/object/' . $obj->id . '/datastream/TN/view';
  }
}

function islandora_newspaper_search_inside_preprocess_islandora_newspaper(&$variables) {
  module_load_include('inc', 'islandora_newspaper_search_inside' ,'includes/block.form');
  $form = drupal_get_form('islandora_newspaper_search_inside_form');
  $variables['search_form_newspaper'] = drupal_render($form);
}


/**
 * Does something.
 *
 * @param string $pid
 *   Object pid.
 * @return array $pages
 *   Array of something.
 */
function islandora_newspaper_search_inside_search($pid) {
  $tuque = islandora_get_tuque_connection();
  $obj = islandora_object_load($pid);
  $query = <<<EOL
SELECT ?a
FROM <#ri>
WHERE
{?a <info:fedora/fedora-system:def/relations-external#isMemberOf> <info:fedora/$pid>}
EOL;
  $issues = $tuque->repository->ri->sparqlQuery($query, 'unlimited');
  $pages = array();
  foreach ($issues as $issue) {
    $issue_pid = $issue['a']['value'];
    $page_query = <<<EOL
SELECT ?a
FROM <#ri>
WHERE
{?a <http://islandora.ca/ontology/relsext#isPageOf> <info:fedora/$issue_pid>}
EOL;
    $result = $tuque->repository->ri->sparqlQuery($page_query, 'unlimited');
    foreach ($result as $key => $value) {
      $pages[] = $value['a']['value'];
    }
  }
  return $pages;
}
